# Generated by Django 4.1.4 on 2023-03-08 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desktops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktops_name', models.CharField(max_length=200, null='true')),
                ('desktops_desc', models.CharField(max_length=200, null='true')),
                ('desktops_price', models.CharField(max_length=200, null='true')),
                ('desktops_image', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, null='true')),
                ('item_desc', models.CharField(max_length=200, null='true')),
                ('item_price', models.CharField(max_length=200, null='true')),
                ('item_image', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptops_name', models.CharField(max_length=200, null='true')),
                ('laptops_desc', models.CharField(max_length=200, null='true')),
                ('laptops_price', models.CharField(max_length=200, null='true')),
                ('laptops_image', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktops', models.ManyToManyField(blank=True, to='techstore.desktops')),
                ('laptops', models.ManyToManyField(blank=True, to='techstore.laptops')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
